apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworldapp
  namespace: argocd
spec:
project: default
source:
  repoURL: 'https://github.com/moinulhuq/repo_public.git'
  path: helloworldapp
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  syncOptions:
    - CreateNamespace=true
    - PruneLast=true


