
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworldapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/moinulhuq/repo_public.git'
    path: helloworldapp
    targetRevision: HEAD
  destination:
    server: https://7EE398324DBEA0B74883866771F26CE3.gr7.ap-southeast-2.eks.amazonaws.com
    namespace: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
